#!/usr/bin/env bash
export V2435I_DEMO_RPOS_HIGH="75"
export V2435I_DEMO_RPOS_LOW="25"
export V2435I_DEMO_SIGNAL_SAMPLER="1"
export V2435F_DEMO_FORCE_ENTRY_SAMPLES="1"
export V2435H_USE_STREAM_PRICE_GUARD="0"
export V2435J_TP_MATRIX_CLOSE_PROOF="1"
export BOLLINGER_BUFFER_CURSOR=${BOLLINGER_BUFFER_CURSOR:-0.0}
export V2433_LIMIT_ARMING_STEP_MULT="8.0"
export V2437_VERSION="V24.3.7_DEMO_MAX_PERMISSION_AUDIT"
export V2437_RUN_ID=${V2437_RUN_ID:-$(date -u +"v2437_%Y%m%dT%H%M%SZ")}
export V2437_ALLOW_EXTREME_BB_DEMO="1"
export V2437_AUDIT_EVERY_DECISION="1"
export V2437_AUDIT_EVERY_ORDER="1"
export V2437_AUDIT_EVERY_RECONCILE="1"
export V2437_RECONCILE_EVERY_CYCLE="1"
export V2437_CLEANUP_VERIFY_LOOP="1"
export V2437_MODULE_HASH_AUDIT="1"
export V2437_PENDING_MAX_AGE_SEC="60"
set -e
cd /home/philippe_vacher06/bot-pivot/live
source venv/bin/activate

export V24_SCALP_ACTIVE=true
export V24_TARGET_TRADES_MIN=${V24_TARGET_TRADES_MIN:-50}
export V24_TARGET_TRADES_MAX=${V24_TARGET_TRADES_MAX:-100}
export V24_MARGIN_BUDGET_EUR=${V24_MARGIN_BUDGET_EUR:-3000}

export V243_STORM_GUARD_ENABLED=${V243_STORM_GUARD_ENABLED:-true}
export V243_STORM_SPREAD_MULT=${V243_STORM_SPREAD_MULT:-3.0}
export V243_STORM_MOVE_STEP_MULT=${V243_STORM_MOVE_STEP_MULT:-2.5}
export V243_STORM_RANGE_STEP_MULT=${V243_STORM_RANGE_STEP_MULT:-3.0}
export V243_STORM_GLOBAL_ALERT_COUNT=${V243_STORM_GLOBAL_ALERT_COUNT:-4}
export V243_STORM_EMERGENCY_CLOSE_ENABLED=${V243_STORM_EMERGENCY_CLOSE_ENABLED:-true}
export V243_STORM_MAX_LOSS_MIN_EUR=${V243_STORM_MAX_LOSS_MIN_EUR:-0.80}
export V243_STORM_MAX_LOSS_PER_OPEN_LEG_EUR=${V243_STORM_MAX_LOSS_PER_OPEN_LEG_EUR:-0.60}
export V243_MAX_LOSS_GUARD_ENABLED=${V243_MAX_LOSS_GUARD_ENABLED:-true}
export V243_MAX_LOSS_1_OPEN_EUR=${V243_MAX_LOSS_1_OPEN_EUR:-1.50}
export V243_MAX_LOSS_2_OPEN_EUR=${V243_MAX_LOSS_2_OPEN_EUR:-3.00}
export V243_MAX_LOSS_3_OPEN_EUR=${V243_MAX_LOSS_3_OPEN_EUR:-5.00}

export HISTORY_MAX_AGE_SEC=${HISTORY_MAX_AGE_SEC:-86400}
export ZONES_MAX_AGE_SEC=${ZONES_MAX_AGE_SEC:-43200}
export MARKETS_MAX_AGE_SEC=${MARKETS_MAX_AGE_SEC:-7200}
export TICK_STREAM_DURATION_SEC=${TICK_STREAM_DURATION_SEC:-45}
export MIN_SPREAD_SAMPLES=${MIN_SPREAD_SAMPLES:-150}
export MAX_TICK_AGE_SEC=${MAX_TICK_AGE_SEC:-20}
export CYCLE_PAUSE_SEC=${CYCLE_PAUSE_SEC:-5}

export BOLLINGER_CURSOR=${BOLLINGER_CURSOR:-0.5}
# V24.3 DEMO ACTIVE -- Bollinger max_dist elargi pour obtenir des LIMIT
# Avec BOLLINGER_CURSOR=0.5, le max_dist final affiche environ 80% de ces valeurs.
export V241_MAX_L1_DISTANCE_ETHUSD=${V241_MAX_L1_DISTANCE_ETHUSD:-35.0}
export V241_MAX_L1_DISTANCE_EURUSD=${V241_MAX_L1_DISTANCE_EURUSD:-0.00125}
export V241_MAX_L1_DISTANCE_EURJPY=${V241_MAX_L1_DISTANCE_EURJPY:-0.225}
export V241_MAX_L1_DISTANCE_OIL_CRUDE=${V241_MAX_L1_DISTANCE_OIL_CRUDE:-0.625}
export V241_MAX_L1_DISTANCE_DE40=${V241_MAX_L1_DISTANCE_DE40:-56.25}
export V241_MAX_L1_DISTANCE_GBPUSD=${V241_MAX_L1_DISTANCE_GBPUSD:-0.00150}
export V241_MAX_L1_DISTANCE_UK100=${V241_MAX_L1_DISTANCE_UK100:-35.0}
export V241_MAX_L1_DISTANCE_GOLD=${V241_MAX_L1_DISTANCE_GOLD:-27.5}

export PENDING_BASKET_MAX_AGE_SEC="300"
export PARTIAL_BASKET_PENDING_MAX_AGE_SEC="300"
export STOP_AIRBAG_STEP_MULT=${STOP_AIRBAG_STEP_MULT:-8.0}
export STOP_AIRBAG_SPREAD_MULT=${STOP_AIRBAG_SPREAD_MULT:-8.0}
export TREND_ENTRY_CURSOR=${TREND_ENTRY_CURSOR:-1.0}
export SAFETY_EXIT_CURSOR=${SAFETY_EXIT_CURSOR:-1.1}
export V24_PNL_AUDIT=true
export V24_TP_SAFETY_MARGIN_EUR=${V24_TP_SAFETY_MARGIN_EUR:-0}

export V24_LIMIT_STOP_RETRY=${V24_LIMIT_STOP_RETRY:-true}
export V24_LIMIT_GUARD_SPREAD_MULT=${V24_LIMIT_GUARD_SPREAD_MULT:-1.5}
export V24_DISABLE_GUARANTEED_STOP_ASSETS="EURUSD,GBPUSD,EURJPY,USDJPY,OIL_CRUDE,OIL_BRENT,BTCUSD,ETHUSD,J225,SILVER"
export V24_FORCE_GUARANTEED_STOP_ASSETS="GOLD"
export V2436_HARD_BOLLINGER_DISTANCE_GUARD="1"
export V2436_REQUIRE_STREAM_SIGNAL_FOR_LIMIT="0"
export V2436_ARMING_CHECK_FAIL_CLOSED="1"
export V2436_CLEANUP_PENDING_ON_SIGNAL="1"
export V2436_MAX_STOP_DISTANCE_EURUSD="0.012"
export V2436_MAX_STOP_DISTANCE_GBPUSD="0.012"

export V24_MARGIN_SELECTION_ENABLED=${V24_MARGIN_SELECTION_ENABLED:-true}
export V24_MAX_BROKER_PENDING_ORDERS=${V24_MAX_BROKER_PENDING_ORDERS:-96}
export V24_MARGIN_BUDGET_EUR=${V24_MARGIN_BUDGET_EUR:-3100}
export MAX_MARGIN_CFD_EUR=${MAX_MARGIN_CFD_EUR:-3100}
export V242_MAX_MARGIN_CFD_EUR=${V242_MAX_MARGIN_CFD_EUR:-3100}
export V242_MIN_AVAILABLE_TO_TRADE_EUR=${V242_MIN_AVAILABLE_TO_TRADE_EUR:-0}

export V243_PENDING_SELECTOR_ENABLED=${V243_PENDING_SELECTOR_ENABLED:-false}
export V243_MARGIN_SELECTOR_ENABLED=${V243_MARGIN_SELECTOR_ENABLED:-true}
export V243_MARGIN_SELECTOR_THRESHOLD_EUR=${V243_MARGIN_SELECTOR_THRESHOLD_EUR:-3100}
export V243_MARGIN_SELECTOR_COOLDOWN_SEC=${V243_MARGIN_SELECTOR_COOLDOWN_SEC:-45}

export V24_ORPHAN_PENDING_MAX_AGE_SEC=${V24_ORPHAN_PENDING_MAX_AGE_SEC:-0}

echo "================================================================"
echo "V2437_RUN_BANNER version=${V2437_VERSION} run_id=${V2437_RUN_ID} utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "V2437_CONFIG_AUDIT arming_mult=${V2433_LIMIT_ARMING_STEP_MULT} sampler=${V2435I_DEMO_SIGNAL_SAMPLER} force_samples=${V2435F_DEMO_FORCE_ENTRY_SAMPLES} stream_guard=${V2435H_USE_STREAM_PRICE_GUARD} require_stream=${V2436_REQUIRE_STREAM_SIGNAL_FOR_LIMIT} pending_ttl=${PENDING_BASKET_MAX_AGE_SEC} max_pending=${V24_MAX_BROKER_PENDING_ORDERS}"
sha256sum run_BOT_PIVOT_07D_SCALP_ACTIVE.sh run_BOT_PIVOT_07D_24_7_DEMO.sh BOT_PIVOT_00_config.py BOT_PIVOT_03_tick_stream.py BOT_PIVOT_04_signal_tick.py BOT_PIVOT_05_cycle_engine.py BOT_PIVOT_06H_execution_demo_guarded.py BOT_PIVOT_06G2_execution_secure.py BOT_PIVOT_06G_execution_from_cycle_state.py BOT_PIVOT_06G1_reconcile_broker.py 2>/dev/null | sed 's/^/V2437_MODULE_HASH /' || true
python3 BOT_PIVOT_06G1_reconcile_broker.py || true
echo "================================================================"

./run_BOT_PIVOT_07D_24_7_DEMO.sh
